# Generated by Django 4.1.5 on 2023-01-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
