# Generated by Django 4.1.5 on 2023-01-19 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billetera', '0003_remove_cuenta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
